# Generated by Django 5.1.4 on 2024-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_datatable_archived_datatable_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatable",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default=True,
                max_length=1,
            ),
        ),
    ]
