# Generated by Django 5.1.4 on 2024-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_datatable_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatable",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")], max_length=1
            ),
        ),
    ]
